INSERT INTO CLIENT_ENTITY (ID, UUID, FIRST_NAME, SECOND_NAME, EMAIL, HASH, CREATED_DATE, IS_DELETED) VALUES (-1, 'client_uuid_1', 'first_name_1', 'second_name_1', 'client_email_1@mail.com', '$2a$10$flldqwXbgRmGFGff.VLR3.5soRebzPOsHkigTGfxHANv2djsFP.N6', '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, FIRST_NAME, SECOND_NAME, EMAIL, HASH, CREATED_DATE, IS_DELETED) VALUES (-2, 'client_uuid_2', 'first_name_2', 'second_name_2', 'client_email_2@mail.com', '$2a$10$flldqwXbgRmGFGff.VLR3.5soRebzPOsHkigTGfxHANv2djsFP.N6', '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, FIRST_NAME, SECOND_NAME, EMAIL, HASH, CREATED_DATE, IS_DELETED) VALUES (-3, 'client_uuid_3', 'first_name_3', 'second_name_3', 'client_email_3@mail.com', '$2a$10$flldqwXbgRmGFGff.VLR3.5soRebzPOsHkigTGfxHANv2djsFP.N6', '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, FIRST_NAME, SECOND_NAME, EMAIL, HASH, CREATED_DATE, IS_DELETED) VALUES (-4, 'client_uuid_4', 'first_name_4', 'second_name_4', 'client_email_4@mail.com', '$2a$10$flldqwXbgRmGFGff.VLR3.5soRebzPOsHkigTGfxHANv2djsFP.N6', '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, FIRST_NAME, SECOND_NAME, EMAIL, HASH, CREATED_DATE, IS_DELETED) VALUES (-5, 'client_uuid_5', 'first_name_5', 'second_name_5', 'client_email_5@mail.com', '$2a$10$flldqwXbgRmGFGff.VLR3.5soRebzPOsHkigTGfxHANv2djsFP.N6', '2024-01-04', 0);
INSERT INTO CLIENT_ENTITY (ID, UUID, FIRST_NAME, SECOND_NAME, EMAIL, HASH, CREATED_DATE, IS_DELETED) VALUES (-6, 'client_uuid_6', 'first_name_6', 'second_name_6', 'client_email_6@mail.com', '$2a$10$flldqwXbgRmGFGff.VLR3.5soRebzPOsHkigTGfxHANv2djsFP.N6', '2024-01-04', 0);

INSERT INTO WEIGHT_RECORD_ENTITY (ID, DATE, CLIENT_ID, WEIGHT_VALUE, CREATED_DATE) VALUES (-1, '2024-01-14', -4, '75.6', '2024-01-14');
INSERT INTO WEIGHT_RECORD_ENTITY (ID, DATE, CLIENT_ID, WEIGHT_VALUE, CREATED_DATE) VALUES (-2, '2024-01-25', -5, '78', '2024-01-14');
INSERT INTO WEIGHT_RECORD_ENTITY (ID, DATE, CLIENT_ID, WEIGHT_VALUE, CREATED_DATE) VALUES (-3, '2024-01-26', -6, '73', '2024-01-14');